apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              memory: "1Gi"
              cpu: "300m"
